# Site settings
title: Jahangeer Iqbal
description: >- # this means to ignore newlines until "baseurl:"
  Lorem isuputor mar lorem usportuni calaridaders for por is form calareios.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://jaiqbal.github.io" # the base hostname & protocol for your site, e.g. http://example.com




# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Erika Lopes
  image    : /assets/images/avatar.jpg
  email    : caluerika@gmail.com
  github   : erikalopes
  twitter  : #
  linkedin : #
  facebook : #


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock