title:              Jahangeer Iqbal
email:              jaiqbal@microsoft.com
description:        Welcome to my blog!
author:             Jahangeer Iqbal
baseurl:            "/"
url:                "https://jaiqbal.github.io"

# Social Profiles
twitter_username:   jaiqbal
github_username:    jaiqbal
facebook_username:  jaiqbal
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
